# Generated by Django 4.1.7 on 2023-03-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Books'},
        ),
    ]
