# Generated by Django 4.1.7 on 2023-03-21 14:24

from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Library_API.json.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowings_book_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowings',
        ),
    ]
