# Generated by Django 4.1.7 on 2023-03-21 14:58

from django.db import migrations, models
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Library_API.json.json")


def reverse_load_fixtures(state, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0006_rename_books_borrowing_book_alter_borrowing_clients'),
        ('books', '0004_remove_book_borrowings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowings',
            field=models.ManyToManyField(related_name='books', to='borrowings.borrowing'),
        ),
    ]
