# Generated by Django 4.1.7 on 2023-03-21 18:37

from django.db import migrations, models
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Library_API.json.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_clients_book_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
        migrations.AddField(
            model_name='book',
            name='Inventory',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
