# Generated by Django 4.1.7 on 2023-03-21 18:40

from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Library_API.json.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_inventory_book_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
