# Generated by Django 4.1.7 on 2023-03-22 19:19

from django.db import migrations
from django.core.management import call_command


def load_fixtures(state, schema_editor):
    call_command("loaddata", "Library_API.json.json")


def reverse_load_fixtures(state, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_inventory_book_inventory'),
    ]

    operations = [
    ]
