# Generated by Django 4.1.7 on 2023-03-19 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
