# Generated by Django 4.1.7 on 2023-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowings_book_clients'),
        ('borrowings', '0002_borrowing_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
