# Generated by Django 4.1.7 on 2023-03-21 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowings', '0004_borrowing_clients_borrowing_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='clients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
