# Generated by Django 4.1.7 on 2023-03-21 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_book_borrowings'),
        ('borrowings', '0006_rename_books_borrowing_book_alter_borrowing_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='clients',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
