# Generated by Django 4.1.7 on 2023-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrowings_book_clients'),
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
