# Generated by Django 4.1.7 on 2023-03-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='book',
        ),
    ]
